//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlug.Ext.Network.Sockets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlug.Ext.Network.Sockets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;div class=&quot;row-fluid&quot;&gt;
        ///    &lt;div class=&quot;box&quot;&gt;
        ///        &lt;div class=&quot;span2&quot;&gt;
        ///            &lt;a href=&quot;/&quot;&gt;&lt;img alt=&quot;Network Icon&quot; src=&quot;@Raw(Model.Context.Paths.Assets)images/networks.png&quot;&gt;&lt;/a&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;span8&quot;&gt;
        ///            &lt;p style=&quot;font-size:22.75px; padding-top:10px; text-align:center;&quot;&gt;MultiPlug.Ext.Network.Sockets&lt;/p&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///    @Include(&quot;MultiPlug.Ext.Network.Sockets.NetworkSocketsNavigation&quot;)
        ///
        ///&lt;section class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeRazor {
            get {
                return ResourceManager.GetString("HomeRazor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function (t) { var i = [], e = &quot;dirty&quot;, n = &quot;clean&quot;, s = &quot;dirtyInitialValue&quot;, r = function (t) { var e; return i.forEach(function (i) { i.id === t &amp;&amp; (e = i) }), e }, a = function (i) { i.form.on(&quot;submit&quot;, function () { i.submitting = !0 }), i.options.preventLeaving &amp;&amp; t(window).on(&quot;beforeunload&quot;, function (t) { if (i.isDirty &amp;&amp; !i.submitting) return t.preventDefault(), i.options.leavingMessage }) }, o = function (t) { t.form.find(&quot;input, select, textarea&quot;).on(&quot;change.dirty click.dirty keyup.dirty keydown. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_dirty_min_js {
            get {
                return ResourceManager.GetString("jquery_dirty_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NetworksIcon {
            get {
                object obj = ResourceManager.GetObject("NetworksIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span4&quot;&gt;
        ///                &lt;a style=&quot;line-height: 52px;&quot; href=&quot;#&quot;&gt;&lt;img alt=&quot;Network Logo&quot; src=&quot;@Raw(Model.Context.Paths.Assets)images/networks.png&quot;&gt;&lt;/a&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span3&quot;&gt;
        ///                &lt;p style=&quot;font-size:26px; line-height: 54px; text-align: center; margin: 0px;&quot;&gt;Not Found&lt;/p&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;div class=&quot;row-fluid&quot;&gt;
        ///    &lt;div class=&quot;box&quot;&gt;
        ///        &lt;div class=&quot;span2&quot;&gt;
        ///            &lt;a href=&quot;/&quot;&gt;&lt;img alt=&quot;Network Icon&quot; src=&quot;@Raw(Model.Context.Paths.Assets)images/networks.png&quot;&gt;&lt;/a&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;span8&quot;&gt;
        ///            &lt;p style=&quot;font-size:22.75px; padding-top:10px; text-align:center;&quot;&gt;About&lt;/p&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    @Include(&quot;MultiPlug.Ext.Network.Sockets.NetworkSocketsNavigation&quot;)
        ///
        ///    &lt;di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@functions {
        ///    public string NavLocationIsHome()
        ///    {
        ///        return Model.Context.Paths.Current == Model.Context.Paths.Home ? &quot;active&quot; : string.Empty;
        ///    }
        ///
        ///    public string NavLocationIsSocketClient()
        ///    {
        ///        return Model.Context.Paths.Current.StartsWith(Model.Context.Paths.Home + &quot;socketclient&quot;) ? &quot;active&quot; : string.Empty;
        ///    }
        ///
        ///    public string NavLocationIsSocketEndpoint()
        ///    {
        ///        return Model.Context.Paths.Current.StartsWith(Model.Cont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsNavigation {
            get {
                return ResourceManager.GetString("SettingsNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///@functions
        ///{
        ///    string isCurrentLoggingLevel(int theLevel)
        ///    {
        ///        return (@Model.Extension.Model.LoggingLevel == theLevel) ? &quot;selected&quot; : &quot;&quot;;
        ///    }
        ///
        ///    string isConnected(bool theStatus)
        ///    {
        ///        return (theStatus) ? &quot;Yes&quot; : &quot;No&quot;;
        ///    }
        ///
        ///    string isChecked(bool theValue)
        ///    {
        ///        return (theValue) ? &quot;checked&quot; : &quot;&quot;;
        ///    }
        ///}
        ///@{
        ///    string[][] WriteSugestions = new string[][]
        ///    {
        ///        new string[]{ &quot;\\u0020&quot;, &quot;Space&quot; },
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SocketClientHome {
            get {
                return ResourceManager.GetString("SocketClientHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@functions {
        ///    public string NavLocationIsHome()
        ///    {
        ///        return Model.Context.Paths.Current == Model.Context.Paths.Home + &quot;socketclient/&quot; ? &quot;active&quot; : string.Empty;
        ///    }
        ///
        ///    public string NavLocationIsSetup()
        ///    {
        ///        return Model.Context.Paths.Current == Model.Context.Paths.Home + &quot;socketclient/setup/&quot; ? &quot;active&quot; : string.Empty;
        ///    }
        ///}
        ///&lt;div class=&quot;row-fluid&quot;&gt;
        ///    &lt;ul class=&quot;nav nav-tabs&quot;&gt;
        ///        &lt;li class=&quot;@NavLocationIsHome()&quot;&gt;&lt;a href=&quot;@Raw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SocketClientNavigation {
            get {
                return ResourceManager.GetString("SocketClientNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span2&quot;&gt;
        ///                &lt;a href=&quot;/&quot;&gt;&lt;img alt=&quot;Network Icon&quot; src=&quot;@Raw(Model.Context.Paths.Assets)images/networks.png&quot;&gt;&lt;/a&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span8&quot;&gt;
        ///                &lt;p style=&quot;font-size:22.75px; padding-top:10px; text-align:center;&quot;&gt;Clients&lt;/p&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    @Include(&quot;MultiPlug.Ext.Network.Socke [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SocketClients {
            get {
                return ResourceManager.GetString("SocketClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///@functions
        ///{
        ///    string isEnabled(bool theValue)
        ///    {
        ///        return (theValue) ? &quot;checked&quot; : &quot;&quot;;
        ///    }
        ///}
        ///
        ///@{
        ///    string[][] WriteSugestions = new string[][]
        ///    {
        ///        new string[]{ &quot;\\u0020&quot;, &quot;Space&quot; },
        ///        new string[]{ &quot;\\u0000&quot;, &quot;NUL (Null)&quot; },
        ///        new string[]{ &quot;\\u0001&quot;, &quot;SOH (Start of Heading)&quot; },
        ///        new string[]{ &quot;\\u0002&quot;, &quot;STX (Start of Text)&quot; },
        ///        new string[]{ &quot;\\u0003&quot;, &quot;ETX (End of Text)&quot; },
        ///        new string[]{ &quot;\\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SocketClientSetup {
            get {
                return ResourceManager.GetString("SocketClientSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///@functions
        ///{
        ///    string isCurrentLoggingLevel(int theLevel)
        ///    {
        ///        return (@Model.Extension.Model.LoggingLevel == theLevel) ? &quot;selected&quot; : &quot;&quot;;
        ///    }
        ///    string isChecked(bool theValue)
        ///    {
        ///        return (theValue) ? &quot;checked&quot; : &quot;&quot;;
        ///    }
        ///}
        ///@{
        ///    string[][] WriteSugestions = new string[][]
        ///    {
        ///        new string[]{ &quot;\\u0020&quot;, &quot;Space&quot; },
        ///        new string[]{ &quot;\\u0000&quot;, &quot;NUL (Null)&quot; },
        ///        new string[]{ &quot;\\u0001&quot;, &quot;SOH (Start of Heading)&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SocketEndpointHome {
            get {
                return ResourceManager.GetString("SocketEndpointHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///@functions {
        ///    public string NavLocationIsHome()
        ///    {
        ///        return Model.Context.Paths.Current == Model.Context.Paths.Home + &quot;socketendpoint/&quot; ? &quot;active&quot; : string.Empty;
        ///    }
        ///
        ///    public string NavLocationIsSetup()
        ///    {
        ///        return Model.Context.Paths.Current == Model.Context.Paths.Home + &quot;socketendpoint/setup/&quot; ? &quot;active&quot; : string.Empty;
        ///    }
        ///}
        ///&lt;div class=&quot;row-fluid&quot;&gt;
        ///    &lt;ul class=&quot;nav nav-tabs&quot;&gt;
        ///        &lt;li class=&quot;@NavLocationIsHome()&quot;&gt;&lt;a href=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SocketEndpointNavigation {
            get {
                return ResourceManager.GetString("SocketEndpointNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span2&quot;&gt;
        ///                &lt;a href=&quot;/&quot;&gt;&lt;img alt=&quot;Network Icon&quot; src=&quot;@Raw(Model.Context.Paths.Assets)images/networks.png&quot;&gt;&lt;/a&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span8&quot;&gt;
        ///                &lt;p style=&quot;font-size:22.75px; padding-top:10px; text-align:center;&quot;&gt;Endpoints&lt;/p&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    @Include(&quot;MultiPlug.Ext.Network.Soc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SocketEndpoints {
            get {
                return ResourceManager.GetString("SocketEndpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Base.Http.EdgeApp
        ///
        ///@functions
        ///{
        ///    string isEnabled(bool theValue)
        ///    {
        ///        return (theValue) ? &quot;checked&quot; : &quot;&quot;;
        ///    }
        ///}
        ///
        ///@{
        ///    string[][] WriteSugestions = new string[][]
        ///    {
        ///        new string[]{ &quot;\\u0020&quot;, &quot;Space&quot; },
        ///        new string[]{ &quot;\\u0000&quot;, &quot;NUL (Null)&quot; },
        ///        new string[]{ &quot;\\u0001&quot;, &quot;SOH (Start of Heading)&quot; },
        ///        new string[]{ &quot;\\u0002&quot;, &quot;STX (Start of Text)&quot; },
        ///        new string[]{ &quot;\\u0003&quot;, &quot;ETX (End of Text)&quot; },
        ///        new string[]{ &quot;\\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SocketEndpointSetup {
            get {
                return ResourceManager.GetString("SocketEndpointSetup", resourceCulture);
            }
        }
    }
}
